K <- reactiveVal()
output$selectMsg <- renderPrint({
  if(is.null(input$dataFile)) {
    cat('Expected datafile format (.csv):\n\n')
    cat('"","Ref","Meth1","Meth2",...,"MethN"\n')
    cat('"Syst1","0.1","0.2","0.3",...,"0.4"\n')
    cat('...\n')
    cat('"SystM","0.5","0.6","0.7",...,"0.8"\n\n')
    return()
  }

  cat('Data set : ', input$dataFile[['name']],'\n')

  data = read.csv(
    file=input$dataFile$datapath,
    header=TRUE,
    stringsAsFactors = FALSE,
    check.names = FALSE)

  systems  <<- data[,1]
  rownames(data) = systems
  Ref      <<- data[,2]
  Data     <<- data[,-c(1,2)]
  methList <<- colnames(Data)
  K(length(methList)) # Dynamic size for graphics updates

  if(input$useRelative)
    Errors   <<- (Ref - Data)/Ref
  else
    Errors   <<- Ref - Data


  cat('Errors (first lines)\n')
  print(head(signif(Errors,2),n=5))
  cat('\n')
  cat('Systems  : ', length(systems),'\n')
  cat('Methods  : ', K(),'\n')

})

output$howTo <- renderText({
  '<h4>Short help on tabs:</h4>
  <ul style="list-style-type:none;">
    <li> <b>Data:</b> Choose a csv datafile and
                      decide if relative errors shouls be used.
    <li> <b>Outliers:</b> Detect and select global outliers using a
                     parallel plot. If outliers are selected, they are
                     removed from dataset for further analyses.
    <li> <b>Statistics:</b> Compute summary statistics. Uncertainties
                     and some statistics are generated by bootstrap.
    <li> <b>HistDist:</b> Plot the distribution of errors as function
                     of calculated data and errors histograms.
    <li> <b>ECDFs:</b> Plot the Empirical Cumulated Distribution
                    Functions of absolute errors.
    <li> <b>Correlations:</b> Plot the correlation matrices of the
                    data, errors or statistics.
    <li> <b>Ranking:</b> Plot the Ranking Probability matrix.
    <li> <b>SIP:</b> Plot the Systematic Improvement Probability matrix.
  </ul>'
})
